-- MySQL Script generated by MySQL Workbench
-- Ср 06 дек 2017 19:24:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema enote
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema enote
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enote` DEFAULT CHARACTER SET utf8 ;
USE `enote` ;

-- -----------------------------------------------------
-- Table `enote`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enote`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iduser_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enote`.`notepad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enote`.`notepad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_notepad_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_notepad_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `enote`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enote`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enote`.`note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NULL,
  `content` TEXT NULL,
  `notepad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_note_1_idx` (`notepad_id` ASC),
  CONSTRAINT `fk_note_1`
    FOREIGN KEY (`notepad_id`)
    REFERENCES `enote`.`notepad` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enote`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enote`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enote`.`tag_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enote`.`tag_note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_TagNote_2_idx` (`note_id` ASC),
  INDEX `fk_TagNote_1_idx` (`tag_id` ASC),
  CONSTRAINT `fk_TagNote_1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `enote`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TagNote_2`
    FOREIGN KEY (`note_id`)
    REFERENCES `enote`.`note` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
